on: [push, pull_request, pull_request_target]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint Lua
    steps:
      - uses: actions/checkout@v1
      - name: luacheck
        id: luacheck
        uses: GoatG33k/fivem-lua-lint-action@v1